INSERT INTO "STATUS" VALUES
(1, 1, 'Imported lead'),
(2, 1, 'Not contacted'),
(3, 1, 'Contacted'),
(4, 1, 'Customer'),
(5, 1, 'Closed (lost)');
INSERT INTO "COMPANY" VALUES
(6, 1, 'Phillips Van Heusen Corp.'),
(7, 1, 'Avaya Inc.'),
(8, 1, 'Laboratory Corporation of America Holdings'),
(9, 1, 'AutoZone, Inc.'),
(10, 1, 'Linens ''n Things Inc.');   
INSERT INTO "CONTACT" VALUES
(11, 1, 'helmi.virtanen@jigrormo.ye', 'Helmi', 'Virtanen', 8, 1),
(12, 1, 'matias.koskinen@zun.mm', 'Matias', 'Koskinen', 7, 5),
(13, 1, 'tiina.laine@capfad.vn', 'Tiina', 'Laine', 6, 3),
(14, 1, 'eino.lahtinen@dec.bn', 'Eino', 'Lahtinen', 10, 3),
(15, 1, 'leena.aalto@bivo.yt', 'Leena', 'Aalto', 6, 4),
(16, 1, 'riitta.rantanen@judbilo.gn', 'Riitta', 'Rantanen', 10, 2),
(17, 1, 'juhani.makela@joraf.wf', 'Juhani', 'Mäkelä', 8, 1),
(18, 1, 'hanna.vainio@kem.tl', 'Hanna', 'Vainio', 8, 5),
(19, 1, 'kaisa.koskinen@odeter.bb', 'Kaisa', 'Koskinen', 6, 1),
(20, 1, 'antti.nieminen@lisohuje.vi', 'Antti', 'Nieminen', 10, 2),
(21, 1, 'laura.jokinen@duod.gy', 'Laura', 'Jokinen', 8, 3),
(22, 1, 'mikko.karkkainen@nowufpus.ph', 'Mikko', 'Kärkkäinen', 7, 1),
(23, 1, 'sofia.heikkila@kagu.hr', 'Sofia', 'Heikkilä', 9, 4),
(24, 1, 'ella.lindstrom@fef.bg', 'Ella', 'Lindström', 9, 3),
(25, 1, 'joonas.nurmi@derwogi.jm', 'Joonas', 'Nurmi', 7, 5),
(26, 1, 'sami.ahonen@wehovuce.gu', 'Sami', 'Ahonen', 7, 3),
(27, 1, 'matti.koski@zamum.bw', 'Matti', 'Koski', 6, 4),
(28, 1, 'vilma.lehtinen@dunebuh.cr', 'Vilma', 'Lehtinen', 8, 1),
(29, 1, 'teemu.ruotsalainen@repiwid.si', 'Teemu', 'Ruotsalainen', 9, 5),
(30, 1, 'pekka.lehto@razuppa.ga', 'Pekka', 'Lehto', 6, 2),
(31, 1, 'anna.jarvinen@kulmenim.ad', 'Anna', 'Järvinen', 9, 3),
(32, 1, 'katri.makela@ib.kg', 'Katri', 'Mäkelä', 9, 1),
(33, 1, 'keijo.kuula@ba.lk', 'Keijo', 'Kuula', 10, 2),
(34, 1, 'petteri.partanen@tohhij.lv', 'Petteri', 'Partanen', 9, 1),
(35, 1, 'jaakko.parkkali@tuvo.sa', 'Jaakko', 'Parkkali', 9, 1);
INSERT INTO "CONTACT" VALUES
(36, 1, 'kaarina.vuori@foga.tw', 'Kaarina', 'Vuori', 7, 5),
(37, 1, 'elin.tuomi@uswuzzub.jp', 'Elin', 'Tuomi', 6, 5),
(38, 1, 'katariina.lahti@hivwerip.vc', 'Katariina', 'Lahti', 9, 2),
(39, 1, 'liisa.salo@gugusu.rw', 'Liisa', 'Salo', 8, 4),
(40, 1, 'osmo.karjalainen@zedekak.md', 'Osmo', 'Karjalainen', 7, 3),
(41, 1, 'jari.koivisto@ral.mk', 'Jari', 'Koivisto', 10, 4),
(42, 1, 'sofie.tuominen@turuhu.bh', 'Sofie', 'Tuominen', 10, 1),
(43, 1, 'paavo.laitinen@omjo.et', 'Paavo', 'Laitinen', 8, 4),
(44, 1, 'jenni.koivisto@rig.bh', 'Jenni', 'Koivisto', 9, 3),
(45, 1, 'sanni.pietila@sicewap.org', 'Sanni', 'Pietilä', 6, 1),
(46, 1, 'lasse.makinen@fo.mh', 'Lasse', 'Mäkinen', 9, 5),
(47, 1, 'jonna.kangas@gegijap.na', 'Jonna', 'Kangas', 10, 1),
(48, 1, 'raimo.lehtinen@kuvesa.pe', 'Raimo', 'Lehtinen', 7, 4),
(49, 1, 'elin.jaaskelainen@lapahu.mt', 'Elin', 'Jääskeläinen', 6, 2),
(50, 1, 'johannes.nurminen@zev.ru', 'Johannes', 'Nurminen', 8, 1),
(51, 1, 'hanna.halonen@nabeaga.ni', 'Hanna', 'Halonen', 6, 1),
(52, 1, 'eveliina.hakala@kaot.ps', 'Eveliina', 'Hakala', 6, 5),
(53, 1, 'essi.kuusisto@tawuctuj.cf', 'Essi', 'Kuusisto', 10, 4),
(54, 1, 'markus.miettinen@eh.ru', 'Markus', 'Miettinen', 8, 2),
(55, 1, 'elinor.heinonen@fajjusuz.kr', 'Elinor', 'Heinonen', 7, 5),
(56, 1, 'leevi.vuorinen@pave.cc', 'Leevi', 'Vuorinen', 6, 5),
(57, 1, 'james.hetfield@ispaviw.gt', 'James', 'Hetfield', 7, 2),
(58, 1, 'kirk.hammet@ha.ee', 'Kirk', 'Hammet', 9, 1),
(59, 1, 'essie.adams@iliat.cw', 'Essie', 'Adams', 8, 5),
(60, 1, 'ozzy.osborne@do.ga', 'Ozzy', 'Osborne', 7, 5);